# Generated by Django 4.0.4 on 2022-06-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='color',
            field=models.CharField(default='#999999', max_length=10),
            preserve_default=False,
        ),
    ]
