# Generated by Django 4.0.4 on 2022-06-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_song_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='img',
            field=models.CharField(max_length=4000),
        ),
    ]
