# Generated by Django 4.0.4 on 2022-06-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='img',
            field=models.CharField(max_length=8000),
        ),
        migrations.AlterField(
            model_name='song',
            name='img',
            field=models.CharField(max_length=8000),
        ),
    ]
