# Generated by Django 4.0.4 on 2022-06-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_game_img_alter_song_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='img',
            field=models.CharField(max_length=99999),
        ),
    ]
