# Generated by Django 4.0.4 on 2022-06-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_alter_game_img_alter_song_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='length',
            field=models.CharField(default='1:00', max_length=20),
            preserve_default=False,
        ),
    ]
